
const nav=document.getElementById('nav');
window.addEventListener('scroll',()=>nav.classList.toggle('scrolled',window.scrollY>40));

const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');io.unobserve(e.target)}}),{threshold:.12});
document.querySelectorAll('.reveal').forEach(el=>io.observe(el));

document.querySelectorAll('.faq-q').forEach(q=>{
  q.addEventListener('click',()=>{
    const item=q.parentElement,open=item.classList.contains('open');
    document.querySelectorAll('.faq-item').forEach(i=>{i.classList.remove('open');i.querySelector('.faq-a').style.maxHeight=null});
    if(!open){item.classList.add('open');item.querySelector('.faq-a').style.maxHeight=item.querySelector('.faq-a').scrollHeight+'px'}
  });
});

const LANGS={'en':['🇬🇧','English'],'fa':['🇮🇷','فارسی'],'ar':['🇸🇦','العربية'],'ckb':['🇮🇶','کوردی (سۆرانی)'],'kmr':['🇹🇷','Kurmancî'],'ru':['🇷🇺','Русский'],'es':['🇪🇸','Español'],'fr':['🇫🇷','Français'],'de':['🇩🇪','Deutsch'],'zh':['🇨🇳','中文']};
const CL={
en:{navF:'Features',navS:'Super-App',navM:'Markets',navP:'Pricing',navQ:'FAQ',navOpen:'Open App',ln:'Language',
chip1:'✦ One account, everything',chip2:'🌍 190+ countries',chip3:'🗣 10 languages',
h1:'Your entire life in <span class="g">one pocket</span>',
sub:'JIB combines money, payments, live markets, schedule, health, news and rewards into a single beautiful daily dashboard. Simple enough for everyone, powerful enough for everything.',
cta1:'Get JIB Free →',cta2:'See how it works',
trust:'4.9/5','trustS':'loved by 2M+ people worldwide',
f1t:'+2.4%',f1s:'Gold today',f2t:'Bill paid',f2s:'2 seconds ago',f3t:'+50 pts',f3s:'Daily rewards',
pm:'Good morning',pd:'Monday · Today',bal:'Balance',gold:'Gold',due:'Due bills',payNow:'Pay now',todayPts:'Today pts',rew:'Reward',ws:'Weekly spending',
bills:'Bills',topup:'Top-up',fx:'FX',gold2:'Gold',
feEyebrow:'One super-app',feH:'Everything you need daily.<br>Nothing you don\'t.',feSub:'Stop juggling 12 apps. JIB unifies them into one intelligent, beautiful dashboard tailored to your life.',
ft1:'Money & Budget',fs1:'Track balances, income, expenses, debts and savings. Automatic monthly budgets and smart insights.',
ft2:'Pay Everything',fs2:'Bills, top-ups, tolls, traffic fines, subscriptions — pay from one place in seconds.',
ft3:'Live Markets',fs3:'Real-time gold, silver, currency, stocks, Forex and crypto with alerts and charts.',
ft4:'Schedule & Reminders',fs4:'Tasks, meetings, meds and important dates with smart reminders that never let you forget.',
ft5:'Daily Health',fs5:'Steps, sleep, water and workouts — a gentle push toward a healthier you.',
ft6:'Your News Feed',fs6:'Local and global news curated to your interests, in your language.',
ft7:'Rewards',fs7:'Earn points for every action. Turn them into cashback, gifts and deals.',
ft8:'AI Assistant',fs8:'Ask anything and JIB replies with answers, actions and advice in seconds.',
ft9:'Bank-Grade Security',fs9:'Encrypted data, biometric login and full control over what you share.',
ssTag:'Payments',ssH:'Pay bills, fines, tolls & top-ups in seconds',ssP:'No more queues, no more separate apps, no more missed deadlines. Find any bill by number or scan, confirm, and it\'s done — with rewards on every payment.',
ssl1b:'Utilities',ssl1s:'Electricity, water, gas, phone, internet',ssl2b:'Transport',ssl2s:'Highway tolls, parking, traffic fines',ssl3b:'Top-ups',ssl3s:'Mobile credit & data bundles instantly',ssl4b:'Payment history',ssl4s:'Everything tracked, searchable, exportable',ssCta:'Start paying now →',
recent:'Recent payments',today:'Today',elec:'Electricity bill',elec2:'Bill #8472591',mobile:'Mobile top-up',mobile2:'IR-MCI +2GB',hway:'Highway toll',hway2:'Auto-pay zone A',traffic:'Traffic fine',traffic2:'Paid & closed',rewEarned:'⭐ Rewards earned','pts':'+75 pts',
mkEyebrow:'Live markets',mkH:'Real-time gold, Forex, crypto & indices',mkP:'Watch the world\'s prices move in real time with charts, alerts and portfolio tracking.',
statLang:'Languages',statCount:'Countries',statUsers:'Active users',statUptime:'Uptime',
prEyebrow:'Pricing',prH:'Start free. Upgrade when you\'re ready.',prP:'No hidden fees. Cancel anytime. Your data stays yours.',
starter:'Starter',pro:'Pro',family:'Family',perM:'/month',mostPop:'MOST POPULAR',
stDesc:'Everything essential for everyday life.',st1:'Money & budget tracking',st2:'Bill & top-up payments',st3:'Basic live markets',st4:'Schedule & reminders',st5:'Rewards program',getStart:'Get started',
proDesc:'For people who want more power & insight.',pro1:'Everything in Starter',pro2:'Advanced market alerts & charts',pro3:'AI assistant & smart insights',pro4:'Unlimited accounts & devices',pro5:'Priority support',pro6:'3× reward points',startPro:'Start Pro →',
famDesc:'One plan for the whole household.',fam1:'Everything in Pro ×5 members',fam2:'Shared budgets & bills',fam3:'Kids safety controls',fam4:'Dedicated family concierge',startFam:'Start Family →',
fqEyebrow:'FAQ',fqH:'Questions, answered',
fq1q:'Is JIB really free?',fq1a:'Yes. The Starter plan is 100% free forever with all essential features. We only charge a small optional fee for Pro power features — no ads, ever, on any plan.',
fq2q:'Which countries does JIB support?',fq2a:'JIB works in 190+ countries with multilingual support and local payment methods wherever available. We add new regions continuously.',
fq3q:'Is my financial data safe?',fq3a:'Your data is encrypted end-to-end with bank-grade security. You always control what you share, and you can export or delete everything at any time.',
fq4q:'Can I use JIB on both phone and computer?',fq4a:'Yes. Your data syncs automatically across all your devices in real time. Start on your phone, continue on your laptop.',
fq5q:'How do I earn rewards?',fq5a:'Earn points for logging in daily, paying bills, completing tasks and more. Redeem points for cashback, discounts, gifts and partner deals.',
ctaH:'Your life has a chic home now.',ctaP:'Join millions who put their entire day in one pocket. Download JIB free today.',
dl:'Download on the',as:'App Store',gi:'Get it on',gp:'Google Play',oi:'Open in',wa:'Web App',
footDesc:'One super-app for your entire life. Built by people who believe daily life should be simple.',
fProduct:'Product',fCompany:'Company',fLegal:'Legal',fP1:'Features',fP2:'Payments',fP3:'Markets',fP4:'Pricing',fC1:'About',fC2:'Careers',fC3:'Press',fC4:'Contact',fL1:'Privacy',fL2:'Terms',fL3:'Security',fL4:'Cookies',
cr:'© 2026 JIB. All rights reserved. Made with care for the whole world 🌍'},
fa:{navF:'قابلیت‌ها',navS:'سوپر اپ',navM:'بازارها',navP:'قیمت‌ها',navQ:'سوالات',navOpen:'باز کردن اپ',ln:'زبان',
chip1:'✦ یک حساب، همه‌چیز',chip2:'🌍 بیش از ۱۹۰ کشور',chip3:'🗣 ۱۰ زبان',
h1:'کل زندگیتان در <span class="g">یک جیب</span>',
sub:'جیب پول، پرداخت‌ها، بازارهای زنده، برنامه، سلامت، اخبار و پاداش‌ها را در یک داشبورد روزانه و زیبا ترکیب می‌کند. به‌اندازه‌ی کافی ساده برای همه، به‌اندازه‌ی کافی قدرتمند برای هرچیز.',
cta1:'دریافت رایگان جیب ←',cta2:'ببینید چطور کار می‌کند',
trust:'۴.۹/۵','trustS':'مورد علاقه‌ی ۲ میلیون+ نفر در جهان',
f1t:'+۲.۴٪',f1s:'طلا امروز',f2t:'قبض پرداخت شد',f2s:'۲ ثانیه پیش',f3t:'+۵۰ امتیاز',f3s:'پاداش روزانه',
pm:'صبح بخیر',pd:'دوشنبه · امروز',bal:'موجودی',gold:'طلا',due:'قبوض معوق',payNow:'پرداخت کن',todayPts:'امتیاز امروز',rew:'پاداش',ws:'خرج هفتگی',
bills:'قبوض',topup:'شارژ',fx:'ارز',gold2:'طلا',
feEyebrow:'یک سوپر اپ',feH:'هرچه هر روز نیاز دارید.<br>و نه چیزی بیشتر.',feSub:'۱۲ اپ را رها کنید. جیب همه را در یک داشبورد هوشمند و زیبا، منطبق با زندگیتان، یکپارچه می‌کند.',
ft1:'پول و بودجه',fs1:'پیگیری موجودی، درآمد، هزینه، بدهی و پس‌انداز. بودجه‌ی ماهانه و بینش‌های هوشمند خودکار.',
ft2:'پرداخت هرچیز',fs2:'قبض، شارژ، عوارض، جریمه و اشتراک — پرداخت از یک‌جا در چند ثانیه.',
ft3:'بازارهای زنده',fs3:'طلا، نقره، ارز، سهام، فارکس و ارز دیجیتال به‌صورت زنده با هشدار و نمودار.',
ft4:'برنامه و یادآور',fs4:'کارها، جلسات، دارو و تاریخ‌های مهم با یادآورهای هوشمند که هرگز فراموش نمی‌کنید.',
ft5:'سلامت روزانه',fs5:'قدم، خواب، آب و ورزش — یک فشار ملایم به‌سوی سلامت بیشتر.',
ft6:'فید اخبار شما',fs6:'اخبار ملی و جهانی متناسب با علایق‌تان، به زبان شما.',
ft7:'پاداش‌ها',fs7:'برای هر اقدام امتیاز بگیرید. آن‌ها را به نقدی، هدیه و تخفیف تبدیل کنید.',
ft8:'دستیار هوشمند',fs8:'هرچیزی بپرسید، جیب در چند ثانیه با پاسخ، اقدام و توصیه جواب می‌دهد.',
ft9:'امنیت بانکی',fs9:'داده‌ی رمزنگاری‌شده، ورود بیومتریک و کنترل کامل بر آنچه به اشتراک می‌گذارید.',
ssTag:'پرداخت',ssH:'پرداخت قبض، جریمه، عوارض و شارژ در چند ثانیه',ssP:'نه صف، نه اپ جدا، نه سررسید ازدست‌رفته. هر قبض را با شماره پیدا کنید یا اسکن کنید، تأیید کنید و تمام — با پاداش بر هر پرداخت.',
ssl1b:'خدمات',ssl1s:'برق، آب، گاز، تلفن، اینترنت',ssl2b:'حمل‌ونقل',ssl2s:'عوارض آزادراه، پارکینگ، جریمه‌ی راهنمایی',ssl3b:'شارژ',ssl3s:'شارژ و بسته‌ی اینترنت موبایل فوری',ssl4b:'تاریخچه‌ی پرداخت',ssl4s:'همه‌چیز ثبت، جستجو و خروجی‌گرفته‌شدنی',ssCta:'شروع پرداخت ←',
recent:'پرداخت‌های اخیر',today:'امروز',elec:'قبض برق',elec2:'قبض #8472591',mobile:'شارژ موبایل',mobile2:'IR-MCI +۲GB',hway:'عوارض آزادراه',hway2:'پرداخت خودکار منطقه A',traffic:'جریمه‌ی راهنمایی',traffic2:'پرداخت و بسته شد',rewEarned:'⭐ پاداش کسب‌شده','pts':'+۷۵ امتیاز',
mkEyebrow:'بازارهای زنده',mkH:'طلا، فارکس، ارز دیجیتال و شاخص‌ها به‌صورت زنده',mkP:'قیمت‌های جهان را با نمودار، هشدار و مدیریت سبد به‌صورت زنده تماشا کنید.',
statLang:'زبان',statCount:'کشور',statUsers:'کاربر فعال',statUptime:'در دسترس بودن',
prEyebrow:'قیمت‌گذاری',prH:'رایگان شروع کنید. هر وقت آماده بودید ارتقا دهید.',prP:'بدون هزینه‌ی پنهان. هر زمان لغو کنید. داده‌ها مال شماست.',
starter:'مبتدی',pro:'حرفه‌ای',family:'خانواده',perM:'/ماه',mostPop:'محبوب‌ترین',
stDesc:'همه‌چیز ضروری برای زندگی روزمره.',st1:'پیگیری پول و بودجه',st2:'پرداخت قبض و شارژ',st3:'بازارهای زنده‌ی پایه',st4:'برنامه و یادآور',st5:'برنامه‌ی پاداش',getStart:'شروع کنید',
proDesc:'برای کسانی که قدرت و بینش بیشتری می‌خواهند.',pro1:'همه‌ی طرح مبتدی',pro2:'هشدار و نمودار پیشرفته‌ی بازار',pro3:'دستیار هوشمند و بینش‌های هوشمند',pro4:'حساب و دستگاه نامحدود',pro5:'پشتیبانی اولویت‌دار',pro6:'۳× امتیاز پاداش',startPro:'شروع حرفه‌ای ←',
famDesc:'یک طرح برای کل خانواده.',fam1:'همه‌ی طرح حرفه‌ای ×۵ عضو',fam2:'بودجه و قبض مشترک',fam3:'کنترل‌های ایمنی کودکان',fam4:'خدمات اختصاصی خانواده',startFam:'شروع خانوادگی ←',
fqEyebrow:'سوالات',fqH:'پرسش‌ها، پاسخ‌داده‌شده',
fq1q:'آیا جیب واقعاً رایگان است؟',fq1a:'بله. طرح مبتدی برای همیشه ۱۰۰٪ رایگان است و همه‌ی امکانات ضروری را دارد. ما فقط برای امکانات قدرتمند حرفه‌ای هزینه‌ی اختیاری کوچک می‌گیریم — و در هیچ طرحی تبلیغ نیست.',
fq2q:'جیب از چه کشورهایی پشتیبانی می‌کند؟',fq2a:'جیب در بیش از ۱۹۰ کشور با پشتیبانی چندزبانه و روش‌های پرداخت محلی (هرجا موجود باشد) کار می‌کند. به‌طور مداوم مناطق جدید اضافه می‌کنیم.',
fq3q:'آیا داده‌ی مالی من امن است؟',fq3a:'داده‌ی شما سرتاسری با امنیت بانکی رمزنگاری می‌شود. همیشه کنترل آنچه به اشتراک می‌گذارید را دارید و می‌توانید هر زمان همه‌چیز را خروجی بگیرید یا حذف کنید.',
fq4q:'آیا می‌توانم هم در موبایل هم در رایانه استفاده کنم؟',fq4a:'بله. داده‌ی شما خودکار و لحظه‌ای میان همه‌ی دستگاه‌ها همگام می‌شود. روی موبایل شروع کنید، روی لپ‌تاپ ادامه دهید.',
fq5q:'چگونه پاداش می‌گیرم؟',fq5a:'با ورود روزانه، پرداخت قبض، تکمیل کارها و بیشتر امتیاز بگیرید. امتیازها را برای نقدی، تخفیف، هدیه و پیشنهادهای همکاران استفاده کنید.',
ctaH:'زندگیتان حالا یک <span style="background:var(--grad);-webkit-background-clip:text;background-clip:text;color:transparent">خانه</span> دارد.',ctaP:'به میلیون‌ها نفری بپیوندید که کل روزشان را در یک جیب می‌گذارند. امروز جیب را رایگان دانلود کنید.',
dl:'دانلود از',as:'اپ استور',gi:'دریافت از',gp:'گوگل پلی',oi:'باز کردن در',wa:'اپ وب',
footDesc:'یک سوپر اپ برای کل زندگیتان. ساخته‌شده توسط کسانی که باور دارند زندگی روزمره باید ساده باشد.',
fProduct:'محصول',fCompany:'شرکت',fLegal:'حقوقی',fP1:'قابلیت‌ها',fP2:'پرداخت',fP3:'بازارها',fP4:'قیمت‌ها',fC1:'درباره',fC2:'فرصت‌های شغلی',fC3:'رسانه',fC4:'تماس',fL1:'حریم خصوصی',fL2:'شرایط',fL3:'امنیت',fL4:'کوکی‌ها',
  cr:'© ۲۰۲۶ جیب. همه‌ی حقوق محفوظ است. ساخته‌شده با دقت برای تمام جهان 🌍'},
ar:{navF:'المزايا',navS:'التطبيق',navM:'الأسواق',navP:'الأسعار',navQ:'الأسئلة',navOpen:'فتح التطبيق',ln:'اللغة',
chip1:'✦ حساب واحد، كل شيء',chip2:'🌍 أكثر من 190 دولة',chip3:'🗣 10 لغات',
h1:'حياتك كلها في <span class="g">جيب واحد</span>',
sub:'يجمع جيب المال، والمدفوعات، والأسواق الحية، والجدول، والصحة، والأخبار والمكافآت في لوحة يومية واحدة جميلة. بسيط بما يكفي للجميع، وقوي بما يكفي لكل شيء.',
cta1:'احصل على جيب مجاناً ←',cta2:'شاهد كيف يعمل',
trust:'4.9/5','trustS':'محبوب من أكثر من 2 مليون شخص حول العالم',
f1t:'+2.4%',f1s:'الذهب اليوم',f2t:'تم دفع الفاتورة',f2s:'قبل ثانيتين',f3t:'+50 نقطة',f3s:'مكافآت يومية',
pm:'صباح الخير',pd:'الاثنين · اليوم',bal:'الرصيد',gold:'الذهب',due:'الفوائد المستحقة',payNow:'ادفع الآن',todayPts:'نقاط اليوم',rew:'مكافأة',ws:'الإنفاق الأسبوعي',
bills:'الفوائد',topup:'شحن',fx:'عملات',gold2:'ذهب',
feEyebrow:'تطبيق واحد',feH:'كل ما تحتاجه يومياً.<br>ولا شيء غير ذلك.',feSub:'توقف عن التنقل بين 12 تطبيقاً. يوحّد جيبها جميعاً في لوحة ذكية وجميلة مصممة حسب حياتك.',
ft1:'المال والميزانية',fs1:'تتبع الأرصدة والدخل والمصروفات والديون والمدخرات. ميزانيات شهرية تلقائية ورؤى ذكية.',
ft2:'ادفع كل شيء',fs2:'الفوائد والشحن والرسوم والغرامات والاشتراكات — ادفع من مكان واحد في ثوانٍ.',
ft3:'أسواق حية',fs3:'الذهب والفضة والعملات والأسهم والفوركس والعملات الرقمية لحظياً مع تنبيهات ورسوم بيانية.',
ft4:'الجدول والتذكيرات',fs4:'المهام والاجتماعات والأدوية والمواعيد المهمة مع تذكيرات ذكية لا تنساها أبداً.',
ft5:'الصحة اليومية',fs5:'الخطوات والنوم والماء والتمارين — دفعة لطيفة نحو حياة أكثر صحة.',
ft6:'مغذى الأخبار',fs6:'أخبار محلية وعالمية منسقة حسب اهتماماتك، بلغتك.',
ft7:'المكافآت',fs7:'اكسب نقاطاً مقابل كل إجراء. حوّلها إلى استرداد نقدي وهدايا وعروض.',
ft8:'المساعد الذكي',fs8:'اسأل أي شيء ويردّ جيب بالإجابات والإجراءات والنصائح في ثوانٍ.',
ft9:'أمان مصرفي',fs9:'بيانات مشفرة وتسجيل دخول بيومتري وتحكم كامل فيما تشاركه.',
ssTag:'المدفوعات',ssH:'ادفع الفوائد والغرامات والرسوم والشحن في ثوانٍ',ssP:'لا مزيد من الطوابير، ولا تطبيقات منفصلة، ولا مواعيد ضائعة. ابحث عن أي فاتورة بالرقم أو امسحها، أكّد وانتهى — مع مكافآت على كل دفعة.',
ssl1b:'المرافق',ssl1s:'كهرباء، ماء، غاز، هاتف، إنترنت',ssl2b:'النقل',ssl2s:'رسوم الطرق السريعة، مواقف السيارات، غرامات المرور',ssl3b:'الشحن',ssl3s:'رصيد الهاتف وباقات الإنترنت فوراً',ssl4b:'سجل الدفعات',ssl4s:'كل شيء متتبَّع وقابل للبحث والتصدير',ssCta:'ابدأ الدفع الآن ←',
recent:'الدفعات الأخيرة',today:'اليوم',elec:'فاتورة الكهرباء',elec2:'فاتورة #8472591',mobile:'شحن الجوال',mobile2:'IR-MCI +2GB',hway:'رسوم الطريق السريع',hway2:'دفع تلقائي المنطقة أ',traffic:'غرامة مرور',traffic2:'مدفوعة ومغلقة',rewEarned:'⭐ المكافآت المكتسبة','pts':'+75 نقطة',
mkEyebrow:'أسواق حية',mkH:'الذهب والفوركس والعملات الرقمية والمؤشرات لحظياً',mkP:'شاهد أسعار العالم تتحرك لحظياً مع رسوم بيانية وتنبيهات وتتبع للمحفظة.',
statLang:'لغات',statCount:'دول',statUsers:'مستخدمون نشطون',statUptime:'وقت التشغيل',
prEyebrow:'الأسعار',prH:'ابدأ مجاناً. ترقَّ عندما تكون جاهزاً.',prP:'لا رسوم خفية. ألغِ في أي وقت. بياناتك تبقى لك.',
starter:'مبتدئ',pro:'احترافي',family:'عائلة',perM:'/شهر',mostPop:'الأكثر شعبية',
stDesc:'كل ما هو أساسي للحياة اليومية.',st1:'تتبع المال والميزانية',st2:'دفع الفوائد والشحن',st3:'أسواق حية أساسية',st4:'الجدول والتذكيرات',st5:'برنامج المكافآت',getStart:'ابدأ الآن',
proDesc:'لمن يريدون قوة ورؤى أكبر.',pro1:'كل شيء في المبتدئ',pro2:'تنبيهات ورسوم متقدمة',pro3:'مساعد ذكي ورؤى ذكية',pro4:'حسابات وأجهزة غير محدودة',pro5:'دعم ذو أولوية',pro6:'3× نقاط المكافآت',startPro:'ابدأ الاحترافي ←',
famDesc:'خطة واحدة لكل الأسرة.',fam1:'كل شيء في الاحترافي ×5 أعضاء',fam2:'ميزانيات وفواتير مشتركة',fam3:'ضوابط أمان للأطفال',fam4:'خدمة عائلية مخصصة',startFam:'ابدأ العائلي ←',
fqEyebrow:'الأسئلة',fqH:'أسئلة، أجيبت',
fq1q:'هل جيب مجاني حقاً؟',fq1a:'نعم. خطة المبتدئ مجانية 100% للأبد مع كل الميزات الأساسية. نفرض رسوماً اختيارية صغيرة فقط لميزات الاحتراف — ولا إعلانات أبداً على أي خطة.',
fq2q:'ما الدول التي يدعمها جيب؟',fq2a:'يعمل جيب في أكثر من 190 دولة مع دعم متعدد اللغات وطرق دفع محلية حيثما توفرت. نضيف مناطق جديدة باستمرار.',
fq3q:'هل بياناتي المالية آمنة؟',fq3a:'بياناتك مشفرة من النهاية إلى النهاية بأمان مصرفي. تتحكم دائماً فيما تشاركه، ويمكنك تصدير أو حذف كل شيء في أي وقت.',
fq4q:'هل يمكنني استخدامه على الهاتف والحاسوب؟',fq4a:'نعم. بياناتك تتم مزامنتها تلقائياً عبر جميع أجهزتك لحظياً. ابدأ على هاتفك، وواصل على حاسوبك المحمول.',
fq5q:'كيف أكسب مكافآت؟',fq5a:'اكسب نقاطاً لتسجيل الدخول يومياً ودفع الفواتير وإكمال المهام وأكثر. استبدل النقاط باسترداد نقدي وخصومات وهدايا وعروض.',
ctaH:'حياتك أصبح لها الآن <span style="background:var(--grad);-webkit-background-clip:text;background-clip:text;color:transparent">منزل</span>.',ctaP:'انضم إلى الملايين الذين يضعون يومهم كاملاً في جيب واحد. حمّل جيب مجاناً اليوم.',
dl:'حمل من',as:'آب ستور',gi:'احصل عليه من',gp:'غوغل بلاي',oi:'افتح في',wa:'تطبيق الويب',
footDesc:'تطبيق واحد لحياتك كلها. صُنع بواسطة أشخاص يؤمنون أن الحياة اليومية يجب أن تكون بسيطة.',
fProduct:'المنتج',fCompany:'الشركة',fLegal:'قانوني',fP1:'المزايا',fP2:'المدفوعات',fP3:'الأسواق',fP4:'الأسعار',fC1:'عنّا',fC2:'الوظائف',fC3:'الصحافة',fC4:'اتصل',fL1:'الخصوصية',fL2:'الشروط',fL3:'الأمان',fL4:'الكوكيز',
  cr:'© ٢٠٢٦ جيب. جميع الحقوق محفوظة. صُنع بعناية من أجل العالم كله 🌍'},
ckb:{navF:'قابلیتەکان',navS:'سوپر ئەپ',navM:'بازارەکان',navP:'نرخەکان',navQ:'پرسیارەکان',navOpen:'کردنەوەی ئەپ',ln:'زمان',
chip1:'✦ یەک هەژمار، هەموو شتێک',chip2:'🌍 زیاتر لە ١٩٠ وڵات',chip3:'🗣 ١٠ زمان',
h1:'هەموو ژیانت لە <span class="g">یەک گیرفان</span>',
sub:'جیب پارە، پارەدانەکان، بازارە زیندووەکان، بەرنامە، تەندروستی، هەواڵ و خەڵاتەکان لە یەک داشبۆردی ڕۆژانەی جواندا کۆدەکاتەوە. بەسە سادە بۆ هەمووان، بەسە بەهێز بۆ هەموو شتێک.',
cta1:'بەخۆڕایی وەربگرە ←',cta2:'ببینە چۆن کار دەکات',
trust:'٤.٩/٥','trustS':'بەدڵی زیاتر لە ٢ ملیۆن کەس لە جیهاندا',
f1t:'+٢.٤٪',f1s:'زێڕی ئەمڕۆ',f2t:'پارەکە درا',f2s:'٢ چرکە پێش ئێستا',f3t:'+٥٠ خاڵ',f3s:'خەڵاتی ڕۆژانە',
pm:'بەیانی باش',pd:'دووشەممە · ئەمڕۆ',bal:'باقییەت',gold:'زێڕ',due:'فاتورەی ماوەبەسەر',payNow:'پارە بدە',todayPts:'خاڵی ئەمڕۆ',rew:'خەڵات',ws:'خەرجی هەفتانە',
bills:'فاتورەکان',topup:'شارژ',fx:'دراو',gold2:'زێڕ',
feEyebrow:'یەک سوپر ئەپ',feH:'هەموو ئەوەی ڕۆژانە پێویستە.<br>زیادە نەبێت.',feSub:'واز لە ١٢ ئەپ بێنە. جیب هەموویان لە یەک داشبۆردی زیرەک و جوان، گونجاو لەگەڵ ژیانت، یەکدەخات.',
ft1:'پارە و بودجە',fs1:'بەدواداچوونی باقییەت، داهات، خەرجی، قەرز و پاشەکەوت. بودجەی مانگانە و تێگەیشتنی زیرەکانەی خۆکار.',
ft2:'پارەدان بۆ هەموو شتێک',fs2:'فاتورە، شارژ، باج، سزا و بەشداربوون — لە یەک شوێن لە چەند چرکەیەکدا.',
ft3:'بازاری زیندوو',fs3:'زێڕ، زیو، دراو، پشک، فۆرێکس و کریپتۆ بە شێوەی زیندوو لەگەڵ ئاگادارکردنەوە و نەخشە.',
ft4:'بەرنامە و یادخستنەوە',fs4:'کارەکان، کۆبوونەوەکان، دەرمان و بەروارە گرنگەکان لەگەڵ یادخستنەوەی زیرەک کە هەرگیز لەبیرت ناکەن.',
ft5:'تەندروستی ڕۆژانە',fs5:'هەنگاو، خەو، ئاو و وەرزش — پاڵدانێکی نەرم بۆ تەندروستی زیاتر.',
ft6:'هەواڵەکانی تۆ',fs6:'هەواڵی ناوخۆیی و جیهانی بەپێی خواستەکانت، بە زمانی تۆ.',
ft7:'خەڵاتەکان',fs7:'بۆ هەر کردەوەیەک خاڵ وەربگرە. بیکە بە کاشباک، دیاری و بابەت.',
ft8:'یاریدەدەری زیرەک',fs8:'هەرشتێک بپرسە، جیب لە چەند چرکەیەکدا بە وەڵام، کردار و ڕێنمایی وەڵام دەداتەوە.',
ft9:'ئاسایشی بانکی',fs9:'زانیاریی نهێنیکراو، چوونەژوورەوەی بایۆمەتری و کۆنترۆڵی تەواو بەسەر ئەوەی دەبەیت.',
ssTag:'پارەدان',ssH:'پارەدانی فاتورە، سزا، باج و شارژ لە چەند چرکەیەکدا',ssP:'نە ڕیز، نە ئەپی جیاواز، نە کاتی بەسەرچوو. هەر فاتورەیەک بە ژمارە بدۆزەرەوە یان سکان بکە، پشتڕاست بکەرەوە و تەواو — لەگەڵ خەڵات لەسەر هەر پارەدانێک.',
ssl1b:'خزمەتگوزاری',ssl1s:'کارەبا، ئاو، گاز، تەلەفۆن، ئینتەرنێت',ssl2b:'گواستنەوە',ssl2s:'باجی ڕێگای خێرا، پارکینگ، سزای هاتوچۆ',ssl3b:'شارژ',ssl3s:'شارژ و بەستەی ئینتەرنێتی مۆبایل دەستبەجێ',ssl4b:'مێژووی پارەدان',ssl4s:'هەموو شتێک تۆمارکراو، گەڕان و دەرهێنانی بەردەست',ssCta:'دەستبکە بە پارەدان ←',
recent:'پارەدانەکانی دوایی',today:'ئەمڕۆ',elec:'فاتورەی کارەبا',elec2:'فاتورە #8472591',mobile:'شارژی مۆبایل',mobile2:'IR-MCI +٢GB',hway:'باجی ڕێگای خێرا',hway2:'پارەدانی خۆکار ناوچەی A',traffic:'سزای هاتوچۆ',traffic2:'پارەدراو و کراوە',rewEarned:'⭐ خەڵاتی بەدەستهاتوو','pts':'+٧٥ خاڵ',
mkEyebrow:'بازاری زیندوو',mkH:'زێڕ، فۆرێکس، کریپتۆ و ئیندیکسەکان بە شێوەی زیندوو',mkP:'نرخی جیهان ببینە لە شێوەی زیندوودا لەگەڵ نەخشە، ئاگادارکردنەوە و بەدواداچوونی پۆرتفۆلیۆ.',
statLang:'زمان',statCount:'وڵات',statUsers:'بەکارهێنەری چالاک',statUptime:'بەردەستبوون',
prEyebrow:'نرخەکان',prH:'بەخۆڕایی دەستپێبکە. کاتێک ئامادە بویت بەرز بکەرەوە.',prP:'بێ خەرجیی شاراوە. هەر کات هەڵوەشێنەرەوە. داتاکە هی تۆیە.',
starter:'سەرەتایی',pro:'پیشەیی',family:'خێزان',perM:'/مانگ',mostPop:'بەناوبانگترین',
stDesc:'هەموو شتێکی پێویست بۆ ژیانی ڕۆژانە.',st1:'بەدواداچوونی پارە و بودجە',st2:'پارەدانی فاتورە و شارژ',st3:'بازاری زیندووی بنەڕەتی',st4:'بەرنامە و یادخستنەوە',st5:'بەرنامەی خەڵات',getStart:'دەستپێبکە',
proDesc:'بۆ ئەوانەی دەیانەوێت زیاتر بەهێز و تێگەیشتن.',pro1:'هەموو شتێک لە سەرەتاییدا',pro2:'ئاگادارکردنەوە و نەخشەی پێشکەوتوو',pro3:'یاریدەدەری زیرەک و تێگەیشتنی زیرەک',pro4:'هەژمار و ئامێری بێسنوور',pro5:'پشتیوانی لەپێش',pro6:'٣× خاڵی خەڵات',startPro:'دەستپێبکە پیشەیی ←',
famDesc:'یەک پلان بۆ هەموو ماڵەکە.',fam1:'هەموو شتێک لە پیشەیی ×٥ ئەندام',fam2:'بودجە و فاتورەی هاوبەش',fam3:'کۆنترۆڵی سەلامەتی منداڵ',fam4:'خزمەتی تایبەتی خێزان',startFam:'دەستپێبکە خێزانی ←',
fqEyebrow:'پرسیارەکان',fqH:'پرسیارەکان، وەڵامدراون',
fq1q:'ئایا جیب بەڕاستی بەخۆڕاییە؟',fq1a:'بەڵێ. پلانی سەرەتایی ١٠٠٪ بەخۆڕاییە هەتاهەتایە لەگەڵ هەموو تایبەتمەندییە پێویستەکان. ئێمە تەنیا بۆ تایبەتمەندییە بەهێزەکانی پیشەیی خەرجییەکی هەڵبژاردەیی بچووک دەگرین — و لە هیچ پلانێکدا ڕیکلام نییە.',
fq2q:'جیب پشتگیری لە چ وڵاتانە دەکات؟',fq2a:'جیب لە زیاتر لە ١٩٠ وڵات کار دەکات لەگەڵ پشتگیری فرەزمانی و ڕێگاکانی پارەدانی ناوخۆیی هەرکوێ بەردەست بێت. بەردەوام ناوچەی نوێ زیاد دەکەین.',
fq3q:'ئایا زانیاری داراییەکەم سەلامەتە؟',fq3a:'داتاکەت بە ئاسایشی بانکی لە سەرەتاوە بۆ کۆتایی نهێنی دەکرێت. هەمیشە کۆنترۆڵی ئەوەی دەبەیت. دەتوانیت هەر کات هەموو شتێک دەربهێنیت یان بسڕیتەوە.',
fq4q:'ئایا دەتوانم لە مۆبایل و کۆمپیوتەر بەکاری بهێنم؟',fq4a:'بەڵێ. داتاکەت بە شێوەی خۆکار و ڕاستەوخۆ لە نێوان هەموو ئامێرەکاندا هاوبەش دەبێت. لە مۆبایل دەستپێبکە، لە لابتۆپ بەردەوام بە.',
fq5q:'چۆن خەڵات وەردەگرم؟',fq5a:'بۆ چوونەژوورەوەی ڕۆژانە، پارەدانی فاتورە، تەواوکردنی کارەکان و زیاتر خاڵ وەربگرە. خاڵەکان بۆ کاشباک، بابەت، دیاری و پێشنیاری هاوبێکان بەکاربهێنە.',
ctaH:'ژیانت ئێستا <span style="background:var(--grad);-webkit-background-clip:text;background-clip:text;color:transparent">ماڵ</span>ێکی هەیە.',ctaP:'بە ملیۆنان کەسەوە بەشداربە کە هەموو ڕۆژەکەیان لە یەک گیرفاندا دادەنێن. ئەمڕۆ جیب بەخۆڕایی داببەزێنە.',
dl:'دابەزاندن لە',as:'ئاپ ستۆر',gi:'وەرگرتن لە',gp:'گووگڵ پلەی',oi:'کردنەوە لە',wa:'ئەپی وێب',
footDesc:'یەک سوپر ئەپ بۆ هەموو ژیانت. دروستکراو لەلایەن ئەو کەسانەی بڕوایان هەیە ژیانی ڕۆژانە دەبێت سادە بێت.',
fProduct:'بەرهەم',fCompany:'کۆمپانیا',fLegal:'یاسایی',fP1:'قابلیەتەکان',fP2:'پارەدان',fP3:'بازارەکان',fP4:'نرخەکان',fC1:'دەربارە',fC2:'کار',fC3:'ڕاگەیاندن',fC4:'پەیوەندی',fL1:'تایبەتمەندی',fL2:'مەرجەکان',fL3:'ئاسایش',fL4:'کووکیەکان',
cr:'© ٢٠٢٦ جیب. هەموو مافەکان پارێزراون. دروستکراو بە وردی بۆ هەموو جیهان 🌍'},
kmr:{navF:'Taybetmendî',navS:'Super-App',navM:'Bazar',navP:'Biha',navQ:'Pirs',navOpen:'Vekirina Appê',ln:'Ziman',
chip1:'✦ Yek hesab, her tişt',chip2:'🌍 Zêdetirî 190 welat',chip3:'🗣 10 ziman',
h1:'Teva jiyana te di <span class="g">yek berîkê</span> de',
sub:'JIB pere, berdêl, bazarên zindî, bername, tenduristî, nûçe û xelatên di yek dashboarda rojane ya xweşik de kom dike. Ji bo her kesî têra xwe sade, ji bo her tiştî têra xwe bi hêz.',
cta1:'JIB bi belaş bistîne ←',cta2:'Bibîne çawa dixebite',
trust:'4.9/5','trustS':'ji hêla 2M+ kesan li cîhanê ve tê hezkirin',
f1t:'+2.4%',f1s:'Zêr îro',f2t:'Fature hat dayîn',f2s:'2 çirke berê',f3t:'+50 xal',f3s:'Xelatên rojane',
pm:'Beyanîbaş',pd:'Duşem · Îro',bal:'Balans',gold:'Zêr',due:'Fatureyên berdayî',payNow:'Bide',todayPts:'Xalên îro',rew:'Xelat',ws:'Xerckirina hefteyî',
bills:'Fature',topup:'Dagirtin',fx:'Pere',gold2:'Zêr',
feEyebrow:'Yek super-app',feH:'Her tiştê ku rojane pêdivî ye.<br>Ne jî zêdetir.',feSub:'Dev ji 12 appan berde. JIB hemûyan di yek dashboarda jîr û xweşik de, li gor jiyana te, yek dike.',
ft1:'Pere û Budçe',fs1:'Balans, dahat, xerckirin, deyn û teserûfê bişopîne. Budçeyên mehane û têgihiştinên jîr ên otomatîk.',
ft2:'Her Tiştê Bide',fs2:'Fature, dagirtin, bac, ceza û abonetî — ji yek cihî di çirkan de bide.',
ft3:'Bazarên Zindî',fs3:'Zêr, zîv, pere, par, Forex û krîpto bi awayê zindî bi alert û nexşe.',
ft4:'Bername û Bîrxistin',fs4:'Kar, civîn, derman û dîrokên girîng bi bîrxistinên jîr ku tu carî ji bîra te nayên.',
ft5:'Tenduristiya Rojane',fs5:'Gav, xew, av û werzîş — zextiyek nerm ber bi tenduristiyê.',
ft6:'Nûçeyên Te',fs6:'Nûçeyên herêmî û cîhanî li gor berjewendiyên te, bi zimanê te.',
ft7:'Xelat',fs7:'Ji bo her kirinê xal bi dest bixe. Wê bikin kashbek, diyarî û danûstandin.',
ft8:'Alîkarê AI',fs8:'Her tiştî bipirse û JIB di çirkan de bi bersiv, kiryar û şîret bersiv dide.',
ft9:'Ewlehiya Bankî',fs9:'Daneyên şîfrekirî, têketina biyometrîk û kontrola tevahî li ser tiştê ku te parve dike.',
ssTag:'Berdêl',ssH:'Fature, ceza, bac û dagirtinan di çirkan de bide',ssP:'Ne rêz, ne appên cihê, ne dîroka derbasbûyî. Her fatureyê bi hejmarê bibîne an skan bike, pêşniyar bike û qediya — bi xelat li ser her berdêlê.',
ssl1b:'Karûbar',ssl1s:'Elektrîk, av, gaz, telefon, înternet',ssl2b:'Veguhestin',ssl2s:'Bacê rêya bilez, parkkirin, cezayê trafîkê',ssl3b:'Dagirtin',ssl3s:'Krediya mobîl û pakêtên înternetê dêstûr',ssl4b:'Dîroka berdêlê',ssl4s:'Her tişt tê şopandin, lêgerîn û eksport',ssCta:'Niha dest bi berdêlê bike ←',
recent:'Berdêlên dawî',today:'Îro',elec:'Fatureya elektrîkê',elec2:'Fature #8472591',mobile:'Dagirtina mobîl',mobile2:'IR-MCI +2GB',hway:'Bacê rêya bilez',hway2:'Berdêla otomatîk herêma A',traffic:'Cezayê trafîkê',traffic2:'Hat dayîn û hate girtin',rewEarned:'⭐ Xelatên wergirtî','pts':'+75 xal',
mkEyebrow:'Bazarên zindî',mkH:'Zêr, Forex, krîpto û endeks bi awayê zindî',mkP:'Bihayên cîhanê bi awayê zindî bi nexşe, alert û şopandina portfolio bibîne.',
statLang:'Ziman',statCount:'Welat',statUsers:'Bikarhênerên aktîf',statUptime:'Amadebûn',
prEyebrow:'Biha',prH:'Bi belaş dest pê bike. Dema amade bî bilind bike.',prP:'Bê mesrefa veşartî. Her dem betal bike. Daneyên te yê te ne.',
starter:'Destpêk',pro:'Profesyonel',family:'Malbat',perM:'/meh',mostPop:'HERÎ POPULER',
stDesc:'Her tiştê bingehîn ji bo jiyana rojane.',st1:'Şopandina pere û budçeyê',st2:'Berdêla fature û dagirtinê',st3:'Bazarên zindî yên bingehîn',st4:'Bername û bîrxistin',st5:'Bernameya xelatê',getStart:'Dest pê bike',
proDesc:'Ji bo kesên ku hêz û têgihiştinek bêtir dixwazin.',pro1:'Her tişt di Destpêkê de',pro2:'Alert û nexşeyên pêşketî yên bazarê',pro3:'Alîkarê AI û têgihiştinên jîr',pro4:'Hesab û amûrên bêsînor',pro5:'Piştgiriya pêşîn',pro6:'3× xalên xelatê',startPro:'Dest bi Profesyonel bike ←',
famDesc:'Yek plan ji bo teva malbatê.',fam1:'Her tişt di Profesyonel de ×5 endam',fam2:'Budçe û fatureyên parvekirî',fam3:'Kontrolên ewlehiya zarokan',fam4:'Xizmeta malbatê ya taybet',startFam:'Dest bi Malbatê bike ←',
fqEyebrow:'Pirs',fqH:'Pirs, hat bersivdan',
fq1q:'Ma JIB bi rastî belaş e?',fq1a:'Erê. Plana Destpêk 100% belaş e heta hetayê bi hemû taybetmendiyên bingehîn. Em tenê ji bo taybetmendiyên hêzdar ên Profesyonel mesrefek piçûk a vebijarkî digirin — û tu carî reklam, tu planan de.',
fq2q:'Ji kîjan welatan JIB piştgirî dike?',fq2a:'JIB di 190+ welatan de bi piştgiriya pirzimanî û rêbazên dayîna herêmî dixebite. Em bi berdewamî herêmên nû zêde dikin.',
fq3q:'Ma daneyên min ên darayî ewle ne?',fq3a:'Daneyên te bi ewlehiya bankî ya dawî-bi-dawî tê şîfrekirin. Tu her dem kontrol dikî tiştê ku te parve dike û dikarî her dem her tiştî eksport an jê bibe.',
fq4q:'Ma ez dikarim hem li têlefon hem jî li kompîturê bikar bînim?',fq4a:'Erê. Daneyên te bi awayê otomatîk û zindî di nav hemû amûran de hevdeng dibin. Li têlefonê dest pê bike, li laptopê bidomîne.',
fq5q:'Ez çawa xelat qezenc dikim?',fq5a:'Ji bo têketina rojane, dayîna fatureyan, qedandina karan û zêdetir xal bi dest bixe. Xalan ji bo kashbek, daxistin, diyarî û danûstandinan bikar bîne.',
ctaH:'Jiyana te niha <span style="background:var(--grad);-webkit-background-clip:text;background-clip:text;color:transparent">mal</span>ek heye.',ctaP:'Beşdarî milyonan bibe yên ku teva roja xwe di yek berîkê de datînin. Îro JIB bi belaş hişyar bike.',
dl:'Daxistin ji',as:'App Store',gi:'Bistîne ji',gp:'Google Play',oi:'Vekirina di',wa:'Appa Webê',
footDesc:'Yek super-app ji bo teva jiyana te. Ji hêla kesên ku bawer dikin jiyana rojane divê sade be hate çêkirin.',
fProduct:'Berhem',fCompany:'Şirket',fLegal:'Qanûnî',fP1:'Taybetmendî',fP2:'Berdêl',fP3:'Bazar',fP4:'Biha',fC1:'Derbar',fC2:'Kar',fC3:'Çapemenî',fC4:'Têkilî',fL1:'Nepenî',fL2:'Merc',fL3:'Ewlehî',fL4:'Kûkî',
cr:'© 2026 JIB. Hemû maf parastî ne. Bi baldarî ji bo teva cîhanê hat çêkirin 🌍'},
ru:{navF:'Возможности',navS:'Супер-приложение',navM:'Рынки',navP:'Цены',navQ:'Вопросы',navOpen:'Открыть',ln:'Язык',
chip1:'✦ Один аккаунт — всё',chip2:'🌍 190+ стран',chip3:'🗣 10 языков',
h1:'Вся ваша жизнь в <span class="g">одном кармане</span>',
sub:'JIB объединяет деньги, платежи, живые рынки, расписание, здоровье, новости и награды в единую красивую ежедневную панель. Достаточно просто для всех и достаточно мощно для всего.',
cta1:'Получить JIB бесплатно →',cta2:'Посмотреть, как это работает',
trust:'4.9/5','trustS':'любят 2+ млн человек по всему миру',
f1t:'+2.4%',f1s:'Золото сегодня',f2t:'Счёт оплачен',f2s:'2 секунды назад',f3t:'+50 очков',f3s:'Ежедневные награды',
pm:'Доброе утро',pd:'Понедельник · Сегодня',bal:'Баланс',gold:'Золото',due:'Просроченные счета',payNow:'Оплатить',todayPts:'Очки сегодня',rew:'Награда',ws:'Еженедельные траты',
bills:'Счета',topup:'Пополнение',fx:'Валюта',gold2:'Золото',
feEyebrow:'Одно супер-приложение',feH:'Всё, что нужно ежедневно.<br>И ничего лишнего.',feSub:'Хватит держать 12 приложений. JIB объединяет их в один умный красивый интерфейс, созданный под вашу жизнь.',
ft1:'Деньги и бюджет',fs1:'Отслеживайте балансы, доходы, расходы, долги и сбережения. Автоматические месячные бюджеты и умная аналитика.',
ft2:'Платите всё',fs2:'Счета, пополнения, дорожные сборы, штрафы, подписки — оплата из одного места за секунды.',
ft3:'Живые рынки',fs3:'Золото, серебро, валюта, акции, Forex и криптовалюта в реальном времени с оповещениями и графиками.',
ft4:'Расписание и напоминания',fs4:'Задачи, встречи, лекарства и важные даты с умными напоминаниями, которые никогда не дадут забыть.',
ft5:'Ежедневное здоровье',fs5:'Шаги, сон, вода и тренировки — мягкий толчок к более здоровой жизни.',
ft6:'Ваша лента новостей',fs6:'Местные и мировые новости по вашим интересам, на вашем языке.',
ft7:'Награды',fs7:'Получайте очки за каждое действие. Превращайте их в кэшбэк, подарки и скидки.',
ft8:'ИИ-ассистент',fs8:'Спросите что угодно, и JIB ответит советом, действием и рекомендацией за секунды.',
ft9:'Безопасность банковского уровня',fs9:'Зашифрованные данные, биометрический вход и полный контроль над тем, что вы публикуете.',
ssTag:'Платежи',ssH:'Платите счета, штрафы, сборы и пополнения за секунды',ssP:'Больше никаких очередей, отдельных приложений и пропущенных сроков. Найдите любой счёт по номеру или сканируйте, подтвердите — и готово, с наградами за каждый платёж.',
ssl1b:'Коммунальные',ssl1s:'Электричество, вода, газ, телефон, интернет',ssl2b:'Транспорт',ssl2s:'Дорожные сборы, парковка, штрафы',ssl3b:'Пополнения',ssl3s:'Кредит и пакеты данных мгновенно',ssl4b:'История платежей',ssl4s:'Всё отслеживается, ищется и экспортируется',ssCta:'Начать платить →',
recent:'Последние платежи',today:'Сегодня',elec:'Счёт за электричество',elec2:'Счёт #8472591',mobile:'Пополнение телефона',mobile2:'IR-MCI +2GB',hway:'Дорожный сбор',hway2:'Автоплатёж зона A',traffic:'Штраф ГИБДД',traffic2:'Оплачен и закрыт',rewEarned:'⭐ Полученные награды','pts':'+75 очков',
mkEyebrow:'Живые рынки',mkH:'Золото, Forex, криптовалюта и индексы в реальном времени',mkP:'Следите за мировыми ценами в реальном времени с графиками, оповещениями и управлением портфелем.',
statLang:'Языки',statCount:'Страны',statUsers:'Активные пользователи',statUptime:'Аптайм',
prEyebrow:'Цены',prH:'Начните бесплатно. Обновитесь, когда будете готовы.',prP:'Без скрытых комиссий. Отмена в любое время. Данные остаются вашими.',
starter:'Старт',pro:'Про',family:'Семья',perM:'/мес',mostPop:'САМЫЙ ПОПУЛЯРНЫЙ',
stDesc:'Всё необходимое для повседневной жизни.',st1:'Отслеживание денег и бюджета',st2:'Оплата счетов и пополнений',st3:'Базовые живые рынки',st4:'Расписание и напоминания',st5:'Программа наград',getStart:'Начать',
proDesc:'Для тех, кто хочет больше мощности и аналитики.',pro1:'Всё в Старте',pro2:'Расширенные оповещения и графики',pro3:'ИИ-ассистент и умная аналитика',pro4:'Неограниченные аккаунты и устройства',pro5:'Приоритетная поддержка',pro6:'3× бонусные очки',startPro:'Начать Про →',
famDesc:'Один тариф для всей семьи.',fam1:'Всё в Про ×5 участников',fam2:'Общие бюджеты и счета',fam3:'Родительский контроль',fam4:'Семейный консьерж',startFam:'Начать Семью →',
fqEyebrow:'Вопросы',fqH:'Вопросы и ответы',
fq1q:'JIB действительно бесплатен?',fq1a:'Да. Тариф Старт бесплатен навсегда со всеми основными функциями. Мы берём небольшую плату только за мощные функции Про — и никакой рекламы ни на одном тарифе.',
fq2q:'В каких странах работает JIB?',fq2a:'JIB работает в 190+ странах с многоязычной поддержкой и локальными способами оплаты. Мы постоянно добавляем новые регионы.',
fq3q:'Безопасны ли мои финансовые данные?',fq3a:'Ваши данные шифруются сквозным шифрованием с безопасностью банковского уровня. Вы всегда контролируете, чем делитесь, и можете экспортировать или удалить всё в любой момент.',
fq4q:'Можно ли пользоваться на телефоне и компьютере?',fq4a:'Да. Данные синхронизируются автоматически и в реальном времени между всеми устройствами. Начните на телефоне, продолжите на ноутбуке.',
fq5q:'Как получать награды?',fq5a:'Получайте очки за ежедневный вход, оплату счетов, выполнение задач и многое другое. Меняйте очки на кэшбэк, скидки, подарки и партнёрские предложения.',
ctaH:'У вашей жизни теперь есть <span style="background:var(--grad);-webkit-background-clip:text;background-clip:text;color:transparent">дом</span>.',ctaP:'Присоединяйтесь к миллионам, которые кладут весь свой день в один карман. Скачайте JIB бесплатно сегодня.',
dl:'Скачать из',as:'App Store',gi:'Получить в',gp:'Google Play',oi:'Открыть в',wa:'Веб-приложение',
footDesc:'Одно супер-приложение для всей вашей жизни. Создано людьми, верящими, что повседневная жизнь должна быть простой.',
fProduct:'Продукт',fCompany:'Компания',fLegal:'Правовое',fP1:'Возможности',fP2:'Платежи',fP3:'Рынки',fP4:'Цены',fC1:'О нас',fC2:'Карьера',fC3:'Пресс-центр',fC4:'Контакты',fL1:'Конфиденциальность',fL2:'Условия',fL3:'Безопасность',fL4:'Куки',
cr:'© 2026 JIB. Все права защищены. Сделано с заботой для всего мира 🌍'},
es:{navF:'Funciones',navS:'Super-App',navM:'Mercados',navP:'Precios',navQ:'Preguntas',navOpen:'Abrir',ln:'Idioma',
chip1:'✦ Una cuenta, todo',chip2:'🌍 190+ países',chip3:'🗣 10 idiomas',
h1:'Toda tu vida en <span class="g">un bolsillo</span>',
sub:'JIB combina dinero, pagos, mercados en vivo, agenda, salud, noticias y recompensas en un único tablero diario y hermoso. Simple para todos, potente para todo.',
cta1:'Obtén JIB gratis →',cta2:'Ver cómo funciona',
trust:'4.9/5','trustS':'amado por más de 2M de personas en el mundo',
f1t:'+2.4%',f1s:'Oro hoy',f2t:'Factura pagada',f2s:'Hace 2 segundos',f3t:'+50 pts',f3s:'Recompensas diarias',
pm:'Buenos días',pd:'Lunes · Hoy',bal:'Saldo',gold:'Oro',due:'Facturas vencidas',payNow:'Pagar ahora',todayPts:'Pts hoy',rew:'Recompensa',ws:'Gasto semanal',
bills:'Facturas',topup:'Recarga',fx:'Divisas',gold2:'Oro',
feEyebrow:'Una super-app',feH:'Todo lo que necesitas a diario.<br>Y nada más.',feSub:'Deja de manejar 12 apps. JIB las unifica en un solo tablero inteligente y hermoso, hecho a tu vida.',
ft1:'Dinero y presupuesto',fs1:'Rastrea saldos, ingresos, gastos, deudas y ahorros. Presupuestos mensuales automáticos y perspectivas inteligentes.',
ft2:'Paga todo',fs2:'Facturas, recargas, peajes, multas, suscripciones: paga desde un solo lugar en segundos.',
ft3:'Mercados en vivo',fs3:'Oro, plata, divisas, acciones, Forex y cripto en tiempo real con alertas y gráficos.',
ft4:'Agenda y recordatorios',fs4:'Tareas, reuniones, medicamentos y fechas importantes con recordatorios inteligentes que nunca olvidan.',
ft5:'Salud diaria',fs5:'Pasos, sueño, agua y ejercicio: un empujón suave hacia una vida más sana.',
ft6:'Tu feed de noticias',fs6:'Noticias locales y globales según tus intereses, en tu idioma.',
ft7:'Recompensas',fs7:'Gana puntos por cada acción. Conviértelos en cashback, regalos y ofertas.',
ft8:'Asistente IA',fs8:'Pregunta lo que sea y JIB responde con respuestas, acciones y consejos en segundos.',
ft9:'Seguridad bancaria',fs9:'Datos cifrados, inicio biométrico y control total sobre lo que compartes.',
ssTag:'Pagos',ssH:'Paga facturas, multas, peajes y recargas en segundos',ssP:'Sin colas, sin apps separadas, sin fechas perdidas. Encuentra cualquier factura por número o escanéala, confirma y listo, con recompensas en cada pago.',
ssl1b:'Servicios',ssl1s:'Electricidad, agua, gas, teléfono, internet',ssl2b:'Transporte',ssl2s:'Peajes, estacionamiento, multas de tráfico',ssl3b:'Recargas',ssl3s:'Crédito móvil y paquetes de datos al instante',ssl4b:'Historial de pagos',ssl4s:'Todo rastreado, buscable y exportable',ssCta:'Empieza a pagar →',
recent:'Pagos recientes',today:'Hoy',elec:'Factura de electricidad',elec2:'Factura #8472591',mobile:'Recarga móvil',mobile2:'IR-MCI +2GB',hway:'Peaje',hway2:'Pago automático zona A',traffic:'Multa de tráfico',traffic2:'Pagada y cerrada',rewEarned:'⭐ Recompensas obtenidas','pts':'+75 pts',
mkEyebrow:'Mercados en vivo',mkH:'Oro, Forex, cripto e índices en tiempo real',mkP:'Mira los precios del mundo en tiempo real con gráficos, alertas y seguimiento de cartera.',
statLang:'Idiomas',statCount:'Países',statUsers:'Usuarios activos',statUptime:'Disponibilidad',
prEyebrow:'Precios',prH:'Empieza gratis. Mejora cuando estés listo.',prP:'Sin cargos ocultos. Cancela cuando quieras. Tus datos son tuyos.',
starter:'Starter',pro:'Pro',family:'Familia',perM:'/mes',mostPop:'MÁS POPULAR',
stDesc:'Todo lo esencial para la vida diaria.',st1:'Seguimiento de dinero y presupuesto',st2:'Pago de facturas y recargas',st3:'Mercados en vivo básicos',st4:'Agenda y recordatorios',st5:'Programa de recompensas',getStart:'Empezar',
proDesc:'Para quienes quieren más potencia y perspectiva.',pro1:'Todo en Starter',pro2:'Alertas y gráficos avanzados',pro3:'Asistente IA y perspectivas inteligentes',pro4:'Cuentas y dispositivos ilimitados',pro5:'Soporte prioritario',pro6:'3× puntos de recompensa',startPro:'Empezar Pro →',
famDesc:'Un plan para toda la familia.',fam1:'Todo en Pro ×5 miembros',fam2:'Presupuestos y facturas compartidos',fam3:'Controles de seguridad infantil',fam4:'Conserje familiar dedicado',startFam:'Empezar Familia →',
fqEyebrow:'Preguntas',fqH:'Preguntas, respondidas',
fq1q:'¿JIB realmente es gratis?',fq1a:'Sí. El plan Starter es 100% gratis para siempre con todas las funciones esenciales. Solo cobramos una pequeña tarifa opcional por las funciones Pro, sin anuncios nunca, en ningún plan.',
fq2q:'¿En qué países funciona JIB?',fq2a:'JIB funciona en 190+ países con soporte multilingüe y métodos de pago locales donde estén disponibles. Añadimos regiones nuevas continuamente.',
fq3q:'¿Están seguros mis datos financieros?',fq3a:'Tus datos están cifrados de extremo a extremo con seguridad bancaria. Siempre controlas lo que compartes y puedes exportar o eliminar todo en cualquier momento.',
fq4q:'¿Puedo usarlo en el teléfono y la computadora?',fq4a:'Sí. Tus datos se sincronizan automáticamente en todos tus dispositivos en tiempo real. Empieza en tu teléfono, continúa en tu portátil.',
fq5q:'¿Cómo gano recompensas?',fq5a:'Gana puntos por iniciar sesión diariamente, pagar facturas, completar tareas y más. Canjea puntos por cashback, descuentos, regalos y ofertas.',
ctaH:'Tu vida ahora tiene un <span style="background:var(--grad);-webkit-background-clip:text;background-clip:text;color:transparent">hogar</span>.',ctaP:'Únete a millones que ponen todo su día en un bolsillo. Descarga JIB gratis hoy.',
dl:'Descargar en',as:'App Store',gi:'Obtener en',gp:'Google Play',oi:'Abrir en',wa:'App web',
footDesc:'Una super-app para toda tu vida. Hecha por personas que creen que la vida diaria debe ser simple.',
fProduct:'Producto',fCompany:'Empresa',fLegal:'Legal',fP1:'Funciones',fP2:'Pagos',fP3:'Mercados',fP4:'Precios',fC1:'Acerca',fC2:'Empleo',fC3:'Prensa',fC4:'Contacto',fL1:'Privacidad',fL2:'Términos',fL3:'Seguridad',fL4:'Cookies',
cr:'© 2026 JIB. Todos los derechos reservados. Hecho con cuidado para todo el mundo 🌍'},
fr:{navF:'Fonctionnalités',navS:'Super-App',navM:'Marchés',navP:'Prix',navQ:'FAQ',navOpen:'Ouvrir',ln:'Langue',
chip1:'✦ Un compte, tout',chip2:'🌍 190+ pays',chip3:'🗣 10 langues',
h1:'Toute votre vie dans <span class="g">une poche</span>',
sub:'JIB combine argent, paiements, marchés en direct, agenda, santé, actualités et récompenses dans un tableau de bord quotidien unique et magnifique. Simple pour tous, puissant pour tout.',
cta1:'Obtenir JIB gratuitement →',cta2:'Voir comment ça marche',
trust:'4.9/5','trustS':'adoré par plus de 2M de personnes dans le monde',
f1t:'+2.4%',f1s:'Or aujourd\'hui',f2t:'Facture payée',f2s:'il y a 2 secondes',f3t:'+50 pts',f3s:'Récompenses quotidiennes',
pm:'Bonjour',pd:'Lundi · Aujourd\'hui',bal:'Solde',gold:'Or',due:'Factures dues',payNow:'Payer maintenant',todayPts:'Pts aujourd\'hui',rew:'Récompense',ws:'Dépenses hebdomadaires',
bills:'Factures',topup:'Recharge',fx:'Devises',gold2:'Or',
feEyebrow:'Une super-app',feH:'Tout ce dont vous avez besoin au quotidien.<br>Et rien de plus.',feSub:'Arrêtez de jongler avec 12 apps. JIB les unifie dans un tableau de bord intelligent et magnifique, adapté à votre vie.',
ft1:'Argent et budget',fs1:'Suivez soldes, revenus, dépenses, dettes et épargne. Budgets mensuels automatiques et insights intelligents.',
ft2:'Payez tout',fs2:'Factures, recharges, péages, amendes, abonnements : payez en un seul endroit en quelques secondes.',
ft3:'Marchés en direct',fs3:'Or, argent, devises, actions, Forex et crypto en temps réel avec alertes et graphiques.',
ft4:'Agenda et rappels',fs4:'Tâches, réunions, médicaments et dates importantes avec des rappels intelligents qui n\'oublient jamais.',
ft5:'Santé quotidienne',fs5:'Pas, sommeil, eau et sport : un petit coup de pouce vers une vie plus saine.',
ft6:'Votre flux d\'actualités',fs6:'Actualités locales et mondiales selon vos centres d\'intérêt, dans votre langue.',
ft7:'Récompenses',fs7:'Gagnez des points pour chaque action. Convertissez-les en cashback, cadeaux et offres.',
ft8:'Assistant IA',fs8:'Demandez n\'importe quoi et JIB répond avec réponses, actions et conseils en secondes.',
ft9:'Sécurité de niveau bancaire',fs9:'Données chiffrées, connexion biométrique et contrôle total sur ce que vous partagez.',
ssTag:'Paiements',ssH:'Payez factures, amendes, péages et recharges en secondes',ssP:'Fini les files, les apps séparées et les échéances manquées. Trouvez n\'importe quelle facture par numéro ou scannez-la, confirmez et c\'est fait, avec des récompenses à chaque paiement.',
ssl1b:'Services',ssl1s:'Électricité, eau, gaz, téléphone, internet',ssl2b:'Transport',ssl2s:'Péages, stationnement, amendes',ssl3b:'Recharges',ssl3s:'Crédit mobile et forfaits data instantanés',ssl4b:'Historique des paiements',ssl4s:'Tout est suivi, recherchable et exportable',ssCta:'Commencez à payer →',
recent:'Paiements récents',today:'Aujourd\'hui',elec:'Facture d\'électricité',elec2:'Facture #8472591',mobile:'Recharge mobile',mobile2:'IR-MCI +2GB',hway:'Péage autoroutier',hway2:'Paiement auto zone A',traffic:'Amende de circulation',traffic2:'Payée et clôturée',rewEarned:'⭐ Récompenses gagnées','pts':'+75 pts',
mkEyebrow:'Marchés en direct',mkH:'Or, Forex, crypto et indices en temps réel',mkP:'Regardez les prix du monde bouger en direct avec graphiques, alertes et suivi de portefeuille.',
statLang:'Langues',statCount:'Pays',statUsers:'Utilisateurs actifs',statUptime:'Disponibilité',
prEyebrow:'Prix',prH:'Commencez gratuitement. Passez au niveau supérieur quand vous voulez.',prP:'Pas de frais cachés. Annulez à tout moment. Vos données restent vôtres.',
starter:'Starter',pro:'Pro',family:'Famille',perM:'/mois',mostPop:'LE PLUS POPULAIRE',
stDesc:'Tout l\'essentiel pour la vie quotidienne.',st1:'Suivi argent et budget',st2:'Paiement des factures et recharges',st3:'Marchés en direct de base',st4:'Agenda et rappels',st5:'Programme de récompenses',getStart:'Commencer',
proDesc:'Pour ceux qui veulent plus de puissance et de perspectives.',pro1:'Tout dans Starter',pro2:'Alertes et graphiques avancés',pro3:'Assistant IA et insights intelligents',pro4:'Comptes et appareils illimités',pro5:'Support prioritaire',pro6:'3× points de récompense',startPro:'Démarrer Pro →',
famDesc:'Un plan pour tout le foyer.',fam1:'Tout dans Pro ×5 membres',fam2:'Budgets et factures partagés',fam3:'Contrôles parentaux',fam4:'Concierge familial dédié',startFam:'Démarrer Famille →',
fqEyebrow:'FAQ',fqH:'Questions, réponses',
fq1q:'JIB est-il vraiment gratuit ?',fq1a:'Oui. Le plan Starter est 100% gratuit pour toujours avec toutes les fonctionnalités essentielles. Nous ne facturons qu\'un petit supplément facultatif pour les fonctionnalités Pro, sans publicité, jamais, sur aucun plan.',
fq2q:'Dans quels pays JIB fonctionne-t-il ?',fq2a:'JIB fonctionne dans 190+ pays avec un support multilingue et des méthodes de paiement locales où disponibles. Nous ajoutons de nouvelles régions en continu.',
fq3q:'Mes données financières sont-elles sûres ?',fq3a:'Vos données sont chiffrées de bout en bout avec une sécurité bancaire. Vous contrôlez toujours ce que vous partagez et pouvez tout exporter ou supprimer à tout moment.',
fq4q:'Puis-je l\'utiliser sur téléphone et ordinateur ?',fq4a:'Oui. Vos données se synchronisent automatiquement sur tous vos appareils en temps réel. Commencez sur votre téléphone, continuez sur votre ordinateur portable.',
fq5q:'Comment gagner des récompenses ?',fq5a:'Gagnez des points en vous connectant quotidiennement, en payant des factures, en accomplissant des tâches et plus. Échangez les points contre du cashback, des réductions, des cadeaux et des offres.',
ctaH:'Votre vie a désormais un <span style="background:var(--grad);-webkit-background-clip:text;background-clip:text;color:transparent">foyer</span>.',ctaP:'Rejoignez des millions de personnes qui mettent toute leur journée dans une poche. Téléchargez JIB gratuitement aujourd\'hui.',
dl:'Télécharger sur',as:'App Store',gi:'Obtenir sur',gp:'Google Play',oi:'Ouvrir dans',wa:'App web',
footDesc:'Une super-app pour toute votre vie. Créée par des gens qui croient que la vie quotidienne doit être simple.',
fProduct:'Produit',fCompany:'Entreprise',fLegal:'Légal',fP1:'Fonctionnalités',fP2:'Paiements',fP3:'Marchés',fP4:'Prix',fC1:'À propos',fC2:'Carrières',fC3:'Presse',fC4:'Contact',fL1:'Confidentialité',fL2:'Conditions',fL3:'Sécurité',fL4:'Cookies',
cr:'© 2026 JIB. Tous droits réservés. Fait avec soin pour le monde entier 🌍'},
de:{navF:'Funktionen',navS:'Super-App',navM:'Märkte',navP:'Preise',navQ:'FAQ',navOpen:'Öffnen',ln:'Sprache',
chip1:'✦ Ein Konto, alles',chip2:'🌍 190+ Länder',chip3:'🗣 10 Sprachen',
h1:'Ihr ganzes Leben in <span class="g">einer Tasche</span>',
sub:'JIB vereint Geld, Zahlungen, Live-Märkte, Terminplan, Gesundheit, Nachrichten und Belohnungen in einem schönen täglichen Dashboard. Einfach genug für alle, leistungsstark genug für alles.',
cta1:'JIB kostenlos holen →',cta2:'So funktioniert es',
trust:'4.9/5','trustS':'von über 2 Mio. Menschen weltweit geliebt',
f1t:'+2,4 %',f1s:'Gold heute',f2t:'Rechnung bezahlt',f2s:'vor 2 Sekunden',f3t:'+50 Pkt',f3s:'Tägliche Belohnungen',
pm:'Guten Morgen',pd:'Montag · Heute',bal:'Guthaben',gold:'Gold',due:'Überfällige Rechnungen',payNow:'Jetzt zahlen',todayPts:'Punkte heute',rew:'Belohnung',ws:'Wöchentliche Ausgaben',
bills:'Rechnungen',topup:'Aufladen',fx:'Devisen',gold2:'Gold',
feEyebrow:'Eine Super-App',feH:'Alles, was Sie täglich brauchen.<br>Und nichts mehr.',feSub:'Schluss mit 12 Apps. JIB vereint sie in einem intelligenten, schönen Dashboard, das zu Ihrem Leben passt.',
ft1:'Geld und Budget',fs1:'Verfolgen Sie Kontostände, Einkommen, Ausgaben, Schulden und Ersparnisse. Automatische Monatsbudgets und intelligente Einblicke.',
ft2:'Alles bezahlen',fs2:'Rechnungen, Aufladungen, Maut, Bußgelder, Abos: an einem Ort in Sekunden bezahlen.',
ft3:'Live-Märkte',fs3:'Gold, Silber, Währungen, Aktien, Forex und Krypto in Echtzeit mit Alarmen und Charts.',
ft4:'Terminplan & Erinnerungen',fs4:'Aufgaben, Meetings, Medikamente und wichtige Termine mit intelligenten Erinnerungen, die nie vergessen.',
ft5:'Tägliche Gesundheit',fs5:'Schritte, Schlaf, Wasser und Workouts: ein sanfter Anstoß zu einem gesünderen Ich.',
ft6:'Ihr Nachrichten-Feed',fs6:'Lokale und globale Nachrichten nach Ihren Interessen, in Ihrer Sprache.',
ft7:'Belohnungen',fs7:'Sammeln Sie Punkte für jede Aktion. Machen Sie daraus Cashback, Geschenke und Rabatte.',
ft8:'KI-Assistent',fs8:'Fragen Sie alles und JIB antwortet mit Antworten, Aktionen und Ratschlägen in Sekunden.',
ft9:'Banken-Sicherheit',fs9:'Verschlüsselte Daten, biometrisches Login und volle Kontrolle über das, was Sie teilen.',
ssTag:'Zahlungen',ssH:'Rechnungen, Bußgelder, Maut und Aufladungen in Sekunden bezahlen',ssP:'Keine Schlangen, keine separaten Apps, keine verpassten Fristen. Finden Sie jede Rechnung per Nummer oder scannen Sie sie, bestätigen Sie, fertig – mit Belohnungen für jede Zahlung.',
ssl1b:'Versorgungsbetriebe',ssl1s:'Strom, Wasser, Gas, Telefon, Internet',ssl2b:'Transport',ssl2s:'Autobahnmaut, Parken, Verkehrsbußgelder',ssl3b:'Aufladungen',ssl3s:'Mobilguthaben und Datenpakete sofort',ssl4b:'Zahlungshistorie',ssl4s:'Alles erfasst, durchsuchbar, exportierbar',ssCta:'Jetzt zahlen →',
recent:'Letzte Zahlungen',today:'Heute',elec:'Stromrechnung',elec2:'Rechnung #8472591',mobile:'Mobilaufladung',mobile2:'IR-MCI +2GB',hway:'Autobahnmaut',hway2:'Autozahlung Zone A',traffic:'Verkehrsbußgeld',traffic2:'Bezahlt und geschlossen',rewEarned:'⭐ Verdiente Belohnungen','pts':'+75 Pkt',
mkEyebrow:'Live-Märkte',mkH:'Gold, Forex, Krypto und Indizes in Echtzeit',mkP:'Beobachten Sie die Weltpreise in Echtzeit mit Charts, Alarmen und Portfolio-Nachverfolgung.',
statLang:'Sprachen',statCount:'Länder',statUsers:'Aktive Nutzer',statUptime:'Verfügbarkeit',
prEyebrow:'Preise',prH:'Kostenlos starten. Upgrade, wenn Sie bereit sind.',prP:'Keine versteckten Gebühren. Jederzeit kündbar. Ihre Daten bleiben Ihre.',
starter:'Starter',pro:'Pro',family:'Familie',perM:'/Monat',mostPop:'AM BELIEBTESTEN',
stDesc:'Alles Wesentliche für den Alltag.',st1:'Geld- und Budget-Tracking',st2:'Rechnungen und Aufladungen bezahlen',st3:'Basis-Live-Märkte',st4:'Terminplan & Erinnerungen',st5:'Belohnungsprogramm',getStart:'Loslegen',
proDesc:'Für Menschen, die mehr Leistung und Einblick wollen.',pro1:'Alles im Starter',pro2:'Erweiterte Markt-Alerts und Charts',pro3:'KI-Assistent & intelligente Einblicke',pro4:'Unbegrenzte Konten und Geräte',pro5:'Priorisierter Support',pro6:'3× Belohnungspunkte',startPro:'Pro starten →',
famDesc:'Ein Plan für den ganzen Haushalt.',fam1:'Alles in Pro ×5 Mitglieder',fam2:'Geteilte Budgets und Rechnungen',fam3:'Kindersicherung',fam4:'Dedizierter Familien-Concierge',startFam:'Familie starten →',
fqEyebrow:'FAQ',fqH:'Fragen, beantwortet',
fq1q:'Ist JIB wirklich kostenlos?',fq1a:'Ja. Der Starter-Plan ist für immer 100% kostenlos mit allen wesentlichen Funktionen. Wir berechnen nur eine kleine optionale Gebühr für Pro-Funktionen – keine Werbung, jemals, auf keinem Plan.',
fq2q:'In welchen Ländern funktioniert JIB?',fq2a:'JIB funktioniert in 190+ Ländern mit mehrsprachiger Unterstützung und lokalen Zahlungsmethoden, wo verfügbar. Wir fügen ständig neue Regionen hinzu.',
fq3q:'Sind meine Finanzdaten sicher?',fq3a:'Ihre Daten werden Ende-zu-Ende mit Bankensicherheit verschlüsselt. Sie kontrollieren immer, was Sie teilen, und können jederzeit alles exportieren oder löschen.',
fq4q:'Kann ich es auf Handy und Computer nutzen?',fq4a:'Ja. Ihre Daten synchronisieren automatisch in Echtzeit über alle Geräte. Beginnen Sie am Handy, machen Sie am Laptop weiter.',
fq5q:'Wie verdiene ich Belohnungen?',fq5a:'Sammeln Sie Punkte für tägliches Einloggen, Rechnungszahlungen, das Erledigen von Aufgaben und mehr. Lösen Sie Punkte gegen Cashback, Rabatte, Geschenke und Partnerangebote ein.',
ctaH:'Ihr Leben hat jetzt ein <span style="background:var(--grad);-webkit-background-clip:text;background-clip:text;color:transparent">Zuhause</span>.',ctaP:'Schließen Sie sich Millionen an, die ihren ganzen Tag in eine Tasche stecken. Laden Sie JIB heute kostenlos herunter.',
dl:'Laden von',as:'App Store',gi:'Holen in',gp:'Google Play',oi:'Öffnen in',wa:'Web-App',
footDesc:'Eine Super-App für Ihr ganzes Leben. Von Menschen gebaut, die glauben, dass das Alltagsleben einfach sein sollte.',
fProduct:'Produkt',fCompany:'Unternehmen',fLegal:'Rechtliches',fP1:'Funktionen',fP2:'Zahlungen',fP3:'Märkte',fP4:'Preise',fC1:'Über uns',fC2:'Karriere',fC3:'Presse',fC4:'Kontakt',fL1:'Datenschutz',fL2:'Bedingungen',fL3:'Sicherheit',fL4:'Cookies',
cr:'© 2026 JIB. Alle Rechte vorbehalten. Mit Sorgfalt für die ganze Welt gemacht 🌍'},
zh:{navF:'功能',navS:'超级应用',navM:'行情',navP:'价格',navQ:'常见问题',navOpen:'打开应用',ln:'语言',
chip1:'✦ 一个账户，一切尽在',chip2:'🌍 190+ 个国家',chip3:'🗣 10 种语言',
h1:'你的整个生活，都在<span class="g">一个口袋</span>里',
sub:'JIB 将资金、支付、实时行情、日程、健康、新闻和奖励整合到一个美观的日常面板中。对所有人足够简单，对一切足够强大。',
cta1:'免费获取 JIB →',cta2:'查看运作方式',
trust:'4.9/5','trustS':'全球 200 万+ 人喜爱',
f1t:'+2.4%',f1s:'今日黄金',f2t:'账单已付',f2s:'2 秒前',f3t:'+50 积分',f3s:'每日奖励',
pm:'早上好',pd:'周一 · 今天',bal:'余额',gold:'黄金',due:'待付账单',payNow:'立即支付',todayPts:'今日积分',rew:'奖励',ws:'每周支出',
bills:'账单',topup:'充值',fx:'外汇',gold2:'黄金',
feEyebrow:'一个超级应用',feH:'每天所需的一切。<br>仅此而已。',feSub:'别再同时用好几个应用了。JIB 将它们统一到一个智能、美观、贴合你生活的面板中。',
ft1:'资金与预算',fs1:'跟踪余额、收入、支出、债务和储蓄。自动月度预算和智能洞察。',
ft2:'支付一切',fs2:'账单、充值、过路费、罚款、订阅——在一个地方几秒内完成支付。',
ft3:'实时行情',fs3:'黄金、白银、外汇、股票、Forex 和加密货币实时行情，支持提醒和图表。',
ft4:'日程与提醒',fs4:'任务、会议、用药和重要日期，智能提醒永不遗漏。',
ft5:'日常健康',fs5:'步数、睡眠、饮水与锻炼——向更健康的你温柔推进。',
ft6:'你的新闻流',fs6:'根据你的兴趣精选的本地和全球新闻，使用你的语言。',
ft7:'奖励',fs7:'每次操作都能获得积分。将其转化为返现、礼物和优惠。',
ft8:'AI 助手',fs8:'问任何问题，JIB 都能在几秒内给出答案、操作和建议。',
ft9:'银行级安全',fs9:'加密数据、生物识别登录，并完全控制你分享的内容。',
ssTag:'支付',ssH:'几秒内支付账单、罚款、过路费和充值',ssP:'无需排队，无需单独的应用，不再错过截止日期。按号码查找或扫描任意账单，确认即完成——每次支付都有奖励。',
ssl1b:'公共服务',ssl1s:'电、水、气、电话、网络',ssl2b:'交通',ssl2s:'高速过路费、停车、交通罚款',ssl3b:'充值',ssl3s:'即时话费与流量包',ssl4b:'支付记录',ssl4s:'全部可跟踪、可搜索、可导出',ssCta:'立即开始支付 →',
recent:'近期支付',today:'今天',elec:'电费账单',elec2:'账单 #8472591',mobile:'手机充值',mobile2:'IR-MCI +2GB',hway:'高速过路费',hway2:'A 区自动支付',traffic:'交通罚款',traffic2:'已支付并结清',rewEarned:'⭐ 获得的奖励','pts':'+75 积分',
mkEyebrow:'实时行情',mkH:'黄金、外汇、加密货币和指数的实时行情',mkP:'通过图表、提醒和投资组合跟踪，实时观察世界价格变动。',
statLang:'语言',statCount:'国家',statUsers:'活跃用户',statUptime:'可用性',
prEyebrow:'价格',prH:'免费开始。准备好时再升级。',prP:'无隐藏费用。随时取消。数据始终归你所有。',
starter:'入门版',pro:'专业版',family:'家庭版',perM:'/月',mostPop:'最受欢迎',
stDesc:'日常生活的必备功能。',st1:'资金和预算跟踪',st2:'账单与充值支付',st3:'基础实时行情',st4:'日程与提醒',st5:'奖励计划',getStart:'开始',
proDesc:'适合想要更多功能和洞察的用户。',pro1:'入门版全部功能',pro2:'高级行情提醒与图表',pro3:'AI 助手与智能洞察',pro4:'无限账户和设备',pro5:'优先支持',pro6:'3 倍奖励积分',startPro:'开始专业版 →',
famDesc:'适合整个家庭的一个方案。',fam1:'专业版全部功能 ×5 名成员',fam2:'共享预算和账单',fam3:'儿童安全控制',fam4:'专属家庭管家',startFam:'开始家庭版 →',
fqEyebrow:'常见问题',fqH:'问题，已解答',
fq1q:'JIB 真的免费吗？',fq1a:'是的。入门版永远 100% 免费，包含所有核心功能。我们只为专业版的高级功能收取少量可选费用——任何方案都绝无广告。',
fq2q:'JIB 支持哪些国家？',fq2a:'JIB 在 190+ 个国家可用，提供多语言支持和本地支付方式（如可用）。我们持续增加新的地区。',
fq3q:'我的财务数据安全吗？',fq3a:'你的数据以银行级安全进行端到端加密。你始终控制分享的内容，可随时导出或删除所有数据。',
fq4q:'我可以在手机和电脑上使用吗？',fq4a:'可以。你的数据会在所有设备间实时自动同步。在手机上开始，在笔记本电脑上继续。',
fq5q:'如何获得奖励？',fq5a:'通过每日登录、支付账单、完成任务等获得积分。可将积分兑换为返现、折扣、礼物和伙伴优惠。',
ctaH:'你的生活现在有了一个<span style="background:var(--grad);-webkit-background-clip:text;background-clip:text;color:transparent">家</span>。',ctaP:'加入数百万将一整天装进口袋的人。今天免费下载 JIB。',
dl:'下载于',as:'App Store',gi:'获取于',gp:'Google Play',oi:'打开于',wa:'Web 应用',
footDesc:'用于你整个生活的一个超级应用。由相信日常生活应当简单的人打造。',
fProduct:'产品',fCompany:'公司',fLegal:'法律',fP1:'功能',fP2:'支付',fP3:'行情',fP4:'价格',fC1:'关于',fC2:'招聘',fC3:'新闻',fC4:'联系',fL1:'隐私',fL2:'条款',fL3:'安全',fL4:'Cookie',
cr:'© 2026 JIB。保留所有权利。用心为整个世界打造 🌍'}
};

const LMap={'en':['en','en-US','en-GB'],'fa':['fa','fa-IR'],'ar':['ar','ar-SA'],'ckb':['ckb','ku-ar'],'kmr':['kmr','ku-IR'],'ru':['ru'],'es':['es'],'fr':['fr'],'de':['de'],'zh':['zh']};
let LV=localStorage.getItem('jibLangL');
if(!LV||!CL[LV]){const nav=(navigator.language||'en').toLowerCase();LV='en';for(const c in LMap)if(LMap[c].some(x=>nav.indexOf(x)>=0)){LV=c;break}localStorage.setItem('jibLangL',LV)}
function setLV(code){LV=code;localStorage.setItem('jibLangL',LV);applyL();buildGrid()}
function buildGrid(){const g=document.getElementById('langGrid');g.innerHTML=Object.keys(LANGS).map(c=>`<div class="lang-btn ${c===LV?'active':''}" data-l="${c}"><span class="lf">${LANGS[c][0]}</span><span class="lt"><b>${LANGS[c][1]}</b></span></div>`).join('');g.querySelectorAll('.lang-btn').forEach(b=>b.onclick=()=>{setLV(b.dataset.l);document.getElementById('langModal').classList.remove('show')})}
function applyL(){const d=CL[LV]||CL.en;document.documentElement.lang=LV;document.documentElement.dir=(RTL.indexOf(LV)>=0)?'rtl':'ltr';document.querySelectorAll('[data-l8n]').forEach(el=>{const k=el.getAttribute('data-l8n');if(d[k]!=null)el.textContent=d[k]});const h1=document.getElementById('heroH1');if(h1&&d.h1)h1.innerHTML=d.h1;const ch=document.getElementById('ctaH1');if(ch&&d.ctaH)ch.innerHTML=d.ctaH;const fe=document.getElementById('feH1');if(fe&&d.feH)fe.innerHTML=d.feH;const lf=document.getElementById('langFlag');if(lf)lf.textContent=LANGS[LV][0];const lc=document.getElementById('langCode');if(lc)lc.textContent=LV.toUpperCase();const ll=document.getElementById('lblLang');if(ll)ll.textContent=d.ln}
document.getElementById('langBtn').addEventListener('click',()=>{buildGrid();document.getElementById('langModal').classList.add('show')});
document.getElementById('langModal').addEventListener('click',e=>{if(e.target.id==='langModal')document.getElementById('langModal').classList.remove('show')});
applyL();

if('serviceWorker' in navigator&&location.protocol.indexOf('http')===0){window.addEventListener('load',()=>{navigator.serviceWorker.register('sw.js').catch(()=>{})})}

